Fixes in error handling, split off validation

diff --git a/ppg-commit b/ppg-commit
--- a/ppg-commit
+++ b/ppg-commit
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+PPG_EXEC_PATH=$( dirname $(realpath "${BASH_SOURCE[0]}" ) )
 GIT_EXEC_PATH=$(git --exec-path)
 GIT_DIR=$(git rev-parse --git-dir)
 
@@ -39,7 +40,8 @@ if [ -n "$production_sha1" -a -n "$orig_production_sha1" ]; then
 		$GIT_EXEC_PATH/git-update-ref -m "ppg ff to origin/production" refs/heads/production $orig_production_sha1 $production_sha1 || exit 1
 		production_sha1=$orig_production_sha1
 	elif [[ "$mb" -ne "$origin_production_sha1" ]]; then
-		echo >&2 "ERROR: production and origin/production have diverged!" || exit 1
+		echo >&2 "ERROR: production and origin/production have diverged!"
+		exit 1
 	fi
 fi
 
@@ -47,54 +49,12 @@ if [ -n "$immediate" ]; then
 	# sanity-check we are on master
 	headname=$(git rev-parse --symbolic-full-name --revs-only HEAD)
 	if [ "$headname" -ne "refs/heads/headname" ]; then
-		echo >&2 "ERROR: can only issue --immediate commit from the master branch!" || exit 1
+		echo >&2 "ERROR: can only issue --immediate commit from the master branch!"
+		exit 1
 	fi
 fi
 
-## validate
-syntax_errors=0
-error_msg=$(mktemp /tmp/error_msg.XXXXXX)
-
-if git rev-parse --quiet --verify HEAD > /dev/null
-then
-    against=HEAD
-else
-    # Initial commit: diff against an empty tree object
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
-
-# Get list of new/modified manifest and template files to check (in git index)
-for indexfile in $(git diff-index --diff-filter=AM --name-only --cached $against | egrep '\.(pp|erb)')
-do
-    # Don't check empty files
-    if [ $(git cat-file -s :0:$indexfile) -gt 0 ]
-    then
-        case $indexfile in
-            *.pp )
-                # Check puppet manifest syntax
-                # Puppet 2.7.20 or newer
-                git cat-file blob :0:$indexfile | puppet parser validate > $error_msg ;;
-            *.erb )
-                # Check ERB template syntax
-                # -P : ignore lines which start with "%" 
-                git cat-file blob :0:$indexfile | erb -P -x -T - | ruby -c 2> $error_msg > /dev/null ;;
-        esac
-        if [ "$?" -ne 0 ]
-        then
-            echo -n "$indexfile: "
-            cat $error_msg
-            syntax_errors=`expr $syntax_errors + 1`
-        fi
-    fi
-done
-
-rm -f $error_msg
-
-if [ "$syntax_errors" -ne 0 ]
-then
-    echo "Error: $syntax_errors syntax errors found, aborting commit."
-    exit 1
-fi
+$PPG_EXEC_PATH/ppg-validate-staged-files || exit 1
 
 export PPG_COMMIT=yes
 git commit "${gitcommitargs[@]}" || exit 1
@@ -109,7 +69,8 @@ if [ -n "$immediate" ]; then
 		head_sha1=$(git rev-parse --revs-only master)
 	    mb=$(git merge-base $production_sha1 refs/heads/master)
 		if [[ "$mb" -ne "$production_sha1" ]]; then
-			echo >&2 "ERROR: cannot fast-forward master to production" || exit 1
+			echo >&2 "ERROR: cannot fast-forward master to production"
+			exit 1
 		fi
 		$GIT_EXEC_PATH/git-update-ref -m "ppg immediate commit" refs/heads/production $head_sha1 $production_sha1 || exit 1
 	fi
